define(['pipAPI', 'https://cdn.jsdelivr.net/gh/mjleaumont/newIAT@main/README.md'], function(APIConstructor, iatExtension){
    var API = new APIConstructor();

	return iatExtension({
		category1 : {
			name : 'Mentally Ill', //Will appear in the data.
			title : {
				media : {word : 'Mentally Ill'}, //Name of the category presented in the task.
				css : {color:'#31940F','font-size':'2em'}, //Style of the category title.
				height : 4 //Used to position the "Or" in the combined block.
			}, 
			stimulusMedia : [ //Stimuli content as PIP's media objects
    		    {image : 'Depression.jpg'}, 
    			{image : 'Schizophrenia.jpg'}, 
    			{image : 'Bipolar.jpg'}, 
    			{image : 'OCD.jpg'}, 
			], 
			//Stimulus css (style)
			stimulusCss : {color:'#31940F','font-size':'1.8em'}
		},	
		category2 :	{
			name : 'Physically Ill', //Will appear in the data.
			title : {
				media : {word : 'Physically Ill'}, //Name of the category presented in the task.
				css : {color:'#31940F','font-size':'2em'}, //Style of the category title.
				height : 4 //Used to position the "Or" in the combined block.
			}, 
			stimulusMedia : [ //Stimuli content as PIP's media objects
    		    {image : 'Diabetes.jpg'}, 
    			{image : 'Sclerosis.jpg'}, 
    			{image : 'Palsy.jpg'}, 
    			{image : 'Appendicitis.jpg'}, 
			], 
			//Stimulus css
			stimulusCss : {color:'#31940F','font-size':'1.8em'}
		},	

		base_url : {//Where are your images at?
			image : 'https://github.com/mjleaumont/newIAT/blob/main/'
		} 
	});
});
